[package]
name = "fastgeojson"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
extendr-api = "0.7"
libR-sys = "0.7"
itoa = "1"
ryu = "1"
rayon = "1.10"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"